// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7CmgDeaRhzQfIQhspopxbxFCjeVA2StY',
    appId: '1:737359941676:web:ad5a652a79b0044a570189',
    messagingSenderId: '737359941676',
    projectId: 'ietp-agrinest',
    authDomain: 'ietp-agrinest.firebaseapp.com',
    storageBucket: 'ietp-agrinest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxeDer0yIUdK7TUYH8y720yXbMUWW4TJw',
    appId: '1:737359941676:android:d3b497539c7e8f63570189',
    messagingSenderId: '737359941676',
    projectId: 'ietp-agrinest',
    storageBucket: 'ietp-agrinest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6NWNVbuYGlTgJyZXXyP-WjCcqu4XMkM',
    appId: '1:737359941676:ios:d992c53e9a537d80570189',
    messagingSenderId: '737359941676',
    projectId: 'ietp-agrinest',
    storageBucket: 'ietp-agrinest.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6NWNVbuYGlTgJyZXXyP-WjCcqu4XMkM',
    appId: '1:737359941676:ios:d992c53e9a537d80570189',
    messagingSenderId: '737359941676',
    projectId: 'ietp-agrinest',
    storageBucket: 'ietp-agrinest.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7CmgDeaRhzQfIQhspopxbxFCjeVA2StY',
    appId: '1:737359941676:web:1ce22d6f1c90564f570189',
    messagingSenderId: '737359941676',
    projectId: 'ietp-agrinest',
    authDomain: 'ietp-agrinest.firebaseapp.com',
    storageBucket: 'ietp-agrinest.firebasestorage.app',
  );
}
